### ISSUE TITLE
I2C_rwflag in i2c_dma works strange

### ISSUE THREAD

**Issue by hexaedron** [wagiminator/MCU-Templates#6]
Hi, there is an issue in [i2c_dma.c](https://github.com/wagiminator/MCU-Templates/blob/main/CH32V003/libraries/i2c_dma.c).
The problem is with I2C_rwflag. It works fine when I2C address is even (0x70 for example) and there is an issue when it is odd (0x27 for example).
I think the problem is in [line 67](https://github.com/wagiminator/MCU-Templates/blob/0355b6f0056d1c7e00da2c5946467a60becd60ef/CH32V003/libraries/i2c_dma.c#L67):
```C
I2C_rwflag = addr & 1;
```

**Comment by wagiminator** [comment]
Hi, I2C_start must be called with the 7-bit I2C address (bits[7..1]) together with read/write bit (bit[0]). I2C_rwflag saves the read/write bit IOT know whether a read or a write opereation will follow. This must be known because this MCU handles the stop condition depending on whether it is reading from or writing to the slave. The I2C_start function must be called like I2C_start(I2C_address << 1 | 0) for a writing and I2C_start(I2C_address << 1 | 1) for a reading operation. You can help yourself with these defines:

#define I2C_startRead(addr) I2C_start(addr << 1 | 1)
#define I2C_startWrite(addr) I2C_start(addr << 1 | 0)

I hope this was helpful.

**Comment by hexaedron** [comment]
Got it, thank you!
